swiftlang/swift-foundation-icu

Package.swift
The CRT POSIX deprecation warnings add a significant amount of noise to the build with little value as there is no current plan to migrate the use of the API to the non-deprecated spellings.  Squelch the warnings by defining the macro to silence the issue.
=> build: define `_CRT_SECURE_NO_DEPRECATE` on Windows

Package.swift
Windows requires a newer version of the C++ standard to allow building with the C++ STL that is shipped with MSVC.
=> build: bump C++ standard to C++14 on Windows

Package.swift
Silence the warnings from the deprecation notices when building ICU itself.  These are useful for the users of the API, less the implementation.
=> build: define `U_ATTRIBUTE_DEPRECATED` when building

icuSources/common/aaplbfct.cpp, icuSources/common/tzfile.h
Right now the project does not build on iOS for two reasons:
- The missing `tzfile.h`
- The extra `<NSSystemDirectories.h>` include (which is not available on iOS)
I added the `tzfile.h` from the ICU repo as a fallback and removed the unused import (project builds on iOS, macOS, and Linux without this header).
=> Fixed iOS build failures

icuSources/common/ubidi.cpp, icuSources/common/ubidiimp.h, icuSources/common/ubidiln.cpp
Renamed `Point` to `_Point` to disambiguate.
This is a temporary workaround to unblock CI.
=> Renamed Point to work around the build failure

icuSources/i18n/number_formatimpl.cpp
For some reason the `unit` being passed to `unitIsBaseUnit` is being deallocated before the comparison could finish, resulting `unitIsBaseUnit` always returning `false`.
This is a temporary fix to ensure `unit` is not deallocated while we look into what's happening with the compiler.
=> Temporary fix: capture macros.unit to ensure we are using the right MeasureUnit is used with `initIsBaseUnit`

Package.swift
Timezone support is generally not available on WASI, so disable it. Additionally, the signal and mman needs explicit emulation options.
This is a preparation for upcoming SCF packaging.
=> build: Repair the build on WASI

Package.swift, swift/FoundationICU/FoundationICU.swift
We think that downstream clients may have errors when building the Foundation package if these libraries are not present, since the FoundationICU module re-exports them.
=> Add library targets for the exported/import sub-modules of FoundationICU

Package.swift, swift/FoundationICU/FoundationICU.swift
`_FoundationICU` is considered an implementation detail for SwiftFoundation and other clients should NOT import it directly.
I will tag a new version with this change to update `SwiftFoundation`.
=> Add underscore prefix to all modules in prepration for cmake support

icuSources/CMakeLists.txt
This copies the public headers to a known location in the build tree so that direct clients (before installation) can specify that directory as an include path when not building via a CMake dependency
=> [CMake] Copy headers to known directory for direct client test builds

icuSources/CMakeLists.txt
Remove a direct link to `stdc++` so that the compiler determines which runtime is appropriate to use (which may not be stdc++ on platforms like Windows or Android)
=> [CMake] Remove direct link to stdc++

CMakeLists.txt
This enables some small conveniences when build this project:
- The first change enables `BUILD_SHARED_LIBS` by default so that when unspecified it builds shared libraries (the normal build) instead of the static sdk build (SCL-F already has this set when doing a full build, but this applies when building swift-foundation-icu in isolation)
- The second change re-enables setting `U_ATTRIBUTE_DEPRECATED` to the empty string (disabled in a previous PR due to build failures caused by not setting it quite right) which silences various deprecation warnings throughout the project making the build log much easier to read
=> [CMake] Add small conveniences

icuSources/include/_foundation_unicode/utf_old.h
`U_EXPORT2` uses `__cdecl` which is for functions only.
=> Use U_EXPORT instead of U_EXPORT2 for non-function symbol

Package.swift
Previously we removed this define because it was defined incorrectly and was causing issues with the CMake build. We added it back to the CMake file and this restores it to the package manifest to ignore unnecessary deprecation warnings throughout the project.
=> Silence deprecation warnings

icuSources/CMakeLists.txt
When building the swift-foundation package locally via CMake using a toolchain that contains the `_FoundationICU` module, you currently encounter errors like:
```
/usr/lib/swift/_foundation_unicode/module.modulemap:1:8: error: redefinition of module '_FoundationICU'
1 | module _FoundationICU {
|        `- error: redefinition of module '_FoundationICU'
2 |     header "appendable.h"
3 |     header "brkiter.h"
/Repos/Public/swift-foundation-icu/icuSources/include/_foundation_unicode/module.modulemap:1:8: note: previously defined here
1 | module _FoundationICU {
|        `- note: previously defined here
2 |     header "appendable.h"
3 |     header "brkiter.h"
```
To solve this, we add an explicit `-fmodule-map-file` flag to swift clients which causes clang to prefer the local module over the …
=> [CMake] Resolve module map conflict with duplicate in SDK

icuSources/CMakeLists.txt
Explanation: Allows building the project via CMake outside of the toolchain
Scope: Should only resolve an issue in local, non-toolchain CMake builds
Original PR: https://github.com/apple/swift-foundation-icu/pull/36
Risk: Minimal - minor change to CMake that has been tested
Testing: Testing done via swift-ci toolchain builds and local, standalone CMake builds
Reviewer: @iCharlesHu
=> [6.0] Add explicit modulemap path to take priority over modulemap from SDK

icuSources/i18n/uspoof.cpp, icuSources/include/_foundation_unicode/utypes.h
**Rationale:** When FoundationInternationalization tests are executed, we effectively load two ICU instances into memory: 1) The system ICU loaded by XCTest via system Foundation; 2) The package ICU SwiftFoundation utilizes.
These two ICUs cause symbol collisions for dyld due to the fact that all public C++ symbols have their own namespaces and coalesce across all loaded dylibs. Consequently, we encounter sporadic test failures in SwiftFoundation as dyld arbitrarily selects ICU symbols and occasionally chooses the system one.
To address this issue, we resolved to hide all C++ APIs, ensuring they are not in the same namespace as the system ICU. This solution proves effective for SwiftFoundation, as it does not actually utilize the C++ APIs.
=> Hide all ICU public C++ Symbols

icuSources/i18n/smpdtfmt.cpp
We had a bug in our implementation that would leave `SimpleDateFormat::fUsePlainSpaces` uninitialized on non-Darwin. This would mean that when we read the uninitialized memory, the nondeterministic contents would determine whether date format patterns used U+0020 or U+202F leading to sporadic test failures that didn't account for both variants. This ensures the variable is always initialized to false so that we always get U+202F.
This should allow us to remove hacks like https://github.com/apple/swift-foundation/blob/8a44479120e4ae0ac8cdbf801943daa0d1e874ad/Sources/TestSupport/TestSupport.swift#L246-L274 entirely since we now use a deterministic separator.
=> Ensure that SimpleDateFormat::fUsePlainSpaces is always initialized

icuSources/i18n/smpdtfmt.cpp
Explanation: Fixes a use-before-initialization issue that caused non-deterministic behavior in date formatting
Scope: Ensures the variable is deterministically initialized
Original PR: https://github.com/apple/swift-foundation-icu/pull/40
Risk: Minimal - minor change that's been thoroughly tested
Testing: Testing done via local SwiftPM tests and swift-ci tests
Reviewer: @iCharlesHu
=> [6.0] Ensure that SimpleDateFormat::fUsePlainSpaces is always initialized

CMakeLists.txt, Package.swift, icuSources/common/putilimp.h, icuSources/common/umutex.cpp, icuSources/common/umutex.h, icuSources/common/unifiedcache.cpp, icuSources/i18n/decimfmt.cpp, icuSources/i18n/number_mapper.h, icuSources/i18n/numrange_fluent.cpp, icuSources/include/_foundation_unicode/numberrangeformatter.h, icuSources/include/_foundation_unicode/platform.h
467631d2a7359c12bcf1c2254a3e797471d70b46 cherry-picks [ICU-22838 Add WebAssembly/WASI cross-compilation support](https://github.com/unicode-org/icu/pull/3067)
The original patch is still under review in the upstream ICU project, but it is needed to unblock the swift-foundation build on WebAssembly.
And also adjust CMakeLists.txt and Package.swift to disable timezone and dynamic loading features.
=> Apply WASI support patch against ICU source tree

CMakeLists.txt
Currently cmake unconditionally set `U_TIMEZONE=timezone` for anything non-windows. This breaks building on FreeBSD using cmake. On FreeBSD, we should not set `U_TIMEZONE` at all. https://github.com/swiftlang/swift-foundation-icu/blob/5b6bcf1e163b9f6185b706da2890447b3fcac9fc/icuSources/common/putilimp.h#L127-L129
=> [FreeBSD] Cmake build should not set U_TIMEZONE for FreeBSD

icuSources/CMakeLists.txt
__Explanation:__ Add a linker flag for the upcoming 16 KB page support in Android.
__Scope:__ Only affects Android
__Issue:__ None
__Original PR:__ #71
__Risk:__ None, only affects Android
__Testing:__ Passed trunk and release/6.2 CI and confirmed locally that this fixed the alignment
__Reviewer:__ @compnerd
@parkera, you just merged this to release/6.2, please let me know if you'll need 6.2.0/6.2.1 pulls also from me to get this patch in, or if you will be rebasing those upcoming releases on the 6.2 branch soon instead.
@swift-ci test
=> [6.2.0][CMake] Use new 16 KB page alignment on 64-bit Android (#71)

icuSources/CMakeLists.txt
__Explanation:__ Add a linker flag for the upcoming 16 KB page support in Android.
__Scope:__ Only affects Android
__Issue:__ None
__Original PR:__ #71
__Risk:__ None, only affects Android
__Testing:__ Passed trunk and release/6.2 CI and confirmed locally that this fixed the alignment
__Reviewer:__ @compnerd
@swift-ci test
=> [6.2.1][CMake] Use new 16 KB page alignment on 64-bit Android (#71)
